use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'DKProject_Example' do
  pod 'DKProject', :path => '../'
#  pod 'DKProject'

  pod 'LookinServer', :configurations => ['Debug']

  target 'DKProject_Tests' do
    inherit! :search_paths

    
  end
end
